name: Mark Koh
favicon: null
layout_spectrum: 0.6271663571242243
typography_spectrum: 0.1961583683732897
title: Ultimate Part timer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4555018504615873
  lightness: 0.2255166065879166
  saturation: 0.8647228016052395
  rhythmicContrast: 0.010590212186798453
purpose: []
